// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvahRUSHbEsSJzjN53h_i4GbBMxonsFuE',
    appId: '1:319059663394:web:93356f9ab36fd7f4ba487b',
    messagingSenderId: '319059663394',
    projectId: 'todo-475d2',
    authDomain: 'todo-475d2.firebaseapp.com',
    storageBucket: 'todo-475d2.firebasestorage.app',
    measurementId: 'G-E5DVN1ZTTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpPRaAoo1b8RrnQmdu-0It2MEwx4KRyc',
    appId: '1:319059663394:android:702fc498d0fc3368ba487b',
    messagingSenderId: '319059663394',
    projectId: 'todo-475d2',
    storageBucket: 'todo-475d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2Ff7a5G-yLssFZQAof-Hz3fLGfhb5qU',
    appId: '1:319059663394:ios:734d6036bc1e93e8ba487b',
    messagingSenderId: '319059663394',
    projectId: 'todo-475d2',
    storageBucket: 'todo-475d2.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2Ff7a5G-yLssFZQAof-Hz3fLGfhb5qU',
    appId: '1:319059663394:ios:734d6036bc1e93e8ba487b',
    messagingSenderId: '319059663394',
    projectId: 'todo-475d2',
    storageBucket: 'todo-475d2.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvahRUSHbEsSJzjN53h_i4GbBMxonsFuE',
    appId: '1:319059663394:web:5fb46d8e856898efba487b',
    messagingSenderId: '319059663394',
    projectId: 'todo-475d2',
    authDomain: 'todo-475d2.firebaseapp.com',
    storageBucket: 'todo-475d2.firebasestorage.app',
    measurementId: 'G-3C4RNL3VHE',
  );

}